# Generated by Django 5.2.11 on 2026-06-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SentEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("subject", models.CharField(blank=True, max_length=998)),
                ("from_email", models.CharField(blank=True, max_length=254)),
                ("to", models.TextField(blank=True)),
                ("cc", models.TextField(blank=True)),
                ("bcc", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("success", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
