language: python

python:
  - 3.4
  - 3.5
  - 3.6

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=mahjong_portal.travis_settings

install:
  - cd server
  - pip install -r requirements.pip

before_script:
  - psql -c "CREATE DATABASE travis_db;" -U postgres

script:
  - python manage.py migrate --noinput
  - python manage.py test --noinput