language: python

python:
  - 3.5
  - 3.6

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=leaderboard.settings

install:
  - pip install -r server/requirements.txt

before_script:
  - psql -c "CREATE DATABASE travis_db;" -U postgres

script:
  - python server/manage.py migrate --noinput
  - python server/manage.py test --noinput