language: python

python:
  - 3.6

services:
  - postgresql

before_install:
  - export DB_HOST=localhost
  - export DB_NAME=travis_db
  - export DB_USER=postgres
  - export DB_PASSWORD=

install:
  - cd server
  - pip install -r requirements.pip

before_script:
  - psql -c "CREATE DATABASE $DB_NAME;" -U $DB_USER

script:
  - ../scripts/localize.py < mahjong_portal/settings/local.example.py > mahjong_portal/settings/local.py
  - ./manage.py migrate --noinput
  - ./manage.py test --noinput
