volumes:
  postgres_production_data: {}

services:
  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    env_file:
      - .envs/.production.env
    depends_on:
      - db
    volumes:
      - ./server:/app/
      - ./files/collected_static:/app/collected_static/
      - ./files/whoosh_index:/app/whoosh_index/
      - ./files/tmp:/tmp
      - ./files/shared/:/app/shared/
      - ./files/media:/app/media
    restart: always
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    ports:
      - '6101:6101'
    command: /usr/local/bin/gunicorn mahjong_portal.wsgi --bind=0.0.0.0:6101 --workers=2 --log-level=info --chdir=/app/
    networks:
      - shared
      - default

  cronjobs:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    depends_on:
      - db
    env_file:
      - .envs/.production.env
    volumes:
      - ./files/whoosh_index:/app/whoosh_index/
      - ./files/tmp:/tmp
      - ./files/media:/app/media
    restart: always
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    user: root
    command: ['crond', '-f']

  db:
    image: postgres:15.3-alpine3.18
    env_file:
      - .envs/.production.env
    restart: always
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - postgres_production_data:/var/lib/postgresql/data

networks:
  shared:
    name: pantheon-connect
    external: true
