version: '2'

services:
    web:
        build: .
        environment:
            DB_HOST: db
            DB_NAME: mahjong_portal
            DB_USER: postgres
            DB_PASSWORD: password
        ports:
            - '8000:8000'
        depends_on:
            - db
        volumes:
            - './server:/srv/mahjong-portal'
        command: ./manage.py runserver 0.0.0.0:8000
    db:
        image: postgres:9.6
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: mahjong_portal
            POSTGRES_PASSWORD: password
        volumes:
            - './initdb.d:/docker-entrypoint-initdb.d'
