version: '3'

volumes:
  postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    image: mahjong-portal
    env_file:
      - ./.envs/.local
    depends_on:
      - db
    volumes:
      - ./server/:/app
    ports:
      - '8060:8060'
    command: python manage.py runserver 0.0.0.0:8060

  db:
    image: postgres:13.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local
#    ports:
#      - '5462:5432'
