version: '2'

services:
    web_portal:
        build: .
        environment:
            DB_HOST: db_portal
            DB_NAME: mahjong_portal
            DB_USER: postgres
            DB_PASSWORD: password
            DB_PORT: 5432
        ports:
            - '8010:8010'
        depends_on:
            - db_portal
        volumes:
            - './server:/srv/mahjong-portal'
        command: ./manage.py runserver 0.0.0.0:8010
        tty: true
        stdin_open: true
    db_portal:
        image: postgres:9.6
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: mahjong_portal
            POSTGRES_PASSWORD: password
        volumes:
            - './initdb.d:/files'
        ports:
            - '5438:5432'
