# Generated by Django 5.2.11 on 2026-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0009_club_new_pantheon_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="club",
            name="name_ru",
        ),
        migrations.AddField(
            model_name="club",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="name_de",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
