# Generated by Django 5.2.11 on 2026-05-26 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("player", "0019_remove_player_first_name_ru_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "event_type",
                    models.CharField(choices=[("wm", "WM (WRC)"), ("em", "EM (ERMC)")], default="wm", max_length=2),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Quota Period",
                "verbose_name_plural": "Quota Periods",
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="AustrianRanking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ema_id", models.CharField(max_length=30)),
                ("display_name", models.CharField(max_length=200)),
                ("rank_position", models.PositiveIntegerField()),
                ("total_points", models.PositiveIntegerField(default=0)),
                ("at_points", models.PositiveIntegerField(default=0)),
                ("foreign_points", models.PositiveIntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="austria_rankings",
                        to="player.player",
                    ),
                ),
                (
                    "quota_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="austria_ranking.quotaperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Austrian Ranking",
                "verbose_name_plural": "Austrian Rankings",
                "ordering": ["rank_position"],
            },
        ),
        migrations.CreateModel(
            name="EmaTournamentResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ema_id", models.CharField(max_length=30)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("tournament_name", models.CharField(max_length=255)),
                ("tournament_country_code", models.CharField(max_length=2)),
                ("end_date", models.DateField()),
                ("position", models.PositiveIntegerField()),
                ("player_count", models.PositiveIntegerField()),
                ("points", models.PositiveIntegerField(default=0)),
                ("is_austrian_tournament", models.BooleanField(default=False)),
                (
                    "quota_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ema_results",
                        to="austria_ranking.quotaperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "EMA Tournament Result",
                "verbose_name_plural": "EMA Tournament Results",
                "ordering": ["-end_date"],
                "unique_together": {("quota_period", "ema_id", "tournament_name", "end_date")},
            },
        ),
    ]
