# Generated by Django 5.2.11 on 2026-06-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("austria_ranking", "0006_quotaevent_fixed_seat_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualificationmodeinfo",
            name="info_text_de",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Informationen zum Qualifikationsmodus"
            ),
        ),
        migrations.AlterField(
            model_name="qualificationmodeinfo",
            name="info_text_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Informationen zum Qualifikationsmodus"
            ),
        ),
        migrations.AlterField(
            model_name="quotaevent",
            name="event_info",
            field=models.TextField(
                blank=True,
                help_text="Shown above the quota ranking table on the Rangliste page.",
                null=True,
                verbose_name="Eventinformation",
            ),
        ),
        migrations.AlterField(
            model_name="quotaevent",
            name="event_info_de",
            field=models.TextField(
                blank=True,
                help_text="Shown above the quota ranking table on the Rangliste page.",
                null=True,
                verbose_name="Eventinformation",
            ),
        ),
        migrations.AlterField(
            model_name="quotaevent",
            name="event_info_en",
            field=models.TextField(
                blank=True,
                help_text="Shown above the quota ranking table on the Rangliste page.",
                null=True,
                verbose_name="Eventinformation",
            ),
        ),
    ]
