# Generated by Django 5.2.11 on 2026-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0018_player_is_hide_ms_activity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="first_name_ru",
        ),
        migrations.RemoveField(
            model_name="player",
            name="last_name_ru",
        ),
        migrations.RemoveField(
            model_name="playertitle",
            name="text_ru",
        ),
        migrations.AddField(
            model_name="player",
            name="first_name_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="last_name_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="playertitle",
            name="text_de",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
