# Generated by Django 5.2.11 on 2026-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0020_rename_tournament_numbers_externalratingdelta_game_numbers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalrating",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="externalrating",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="name_ru",
        ),
        migrations.AddField(
            model_name="externalrating",
            name="description_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="externalrating",
            name="name_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="description_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="name_de",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
