# Generated by Django 5.2.11 on 2026-06-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0022_remove_rating_translation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="type",
            field=models.PositiveSmallIntegerField(choices=[(1, "EMA"), (3, "ONLINE")]),
        ),
    ]
