# Generated by Django 5.2.11 on 2026-06-04 12:40

import filebrowser.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="image",
            field=filebrowser.fields.FileBrowseField(
                blank=True, max_length=200, null=True, verbose_name="Image (from media library)"
            ),
        ),
    ]
