# Generated by Django 5.2.11 on 2026-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0019_alter_leaguegame_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="league",
            name="name_ru",
        ),
        migrations.AddField(
            model_name="league",
            name="description_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="league",
            name="name_de",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
