# Generated by Django 5.2.11 on 2026-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0057_tournament_tournament_games_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="registration_description_ru",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="results_description_ru",
        ),
        migrations.AddField(
            model_name="tournament",
            name="name_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="registration_description_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="results_description_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
