# Generated by Django 5.2.11 on 2026-05-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0059_remove_tournament_name_translations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="russian_cup",
        ),
        migrations.AlterField(
            model_name="tournament",
            name="tournament_type",
            field=models.CharField(
                choices=[("ema", "ema"), ("other", "other"), ("online", "online")],
                db_index=True,
                default="ema",
                max_length=10,
            ),
        ),
    ]
