# Generated by Django 5.2.11 on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0060_remove_russian_cup_and_obsolete_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentregistration",
            name="email",
            field=models.EmailField(
                default="",
                help_text="It will be visible only to the administrator",
                max_length=255,
                verbose_name="Email",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tournamentregistration",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="It will be visible only to the administrator",
                max_length=255,
                null=True,
                verbose_name="Phone",
            ),
        ),
    ]
