# Generated by Django 5.2.11 on 2026-06-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0066_tournament_gdpr_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentregistration",
            name="ema_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="European Mahjong Association ID (optional)",
                max_length=50,
                null=True,
                verbose_name="EMA-ID",
            ),
        ),
        migrations.AlterField(
            model_name="onlinetournamentregistration",
            name="registration_country",
            field=models.CharField(max_length=255, null=True, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="contact_info_de",
            field=models.TextField(blank=True, null=True, verbose_name="Contact information"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="contact_info_en",
            field=models.TextField(blank=True, null=True, verbose_name="Contact information"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="gdpr_document",
            field=models.FileField(
                blank=True, null=True, upload_to="tournament/gdpr/", verbose_name="GDPR document (PDF) — direct upload"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="lunch_options_de",
            field=models.TextField(blank=True, null=True, verbose_name="Lunch options"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="lunch_options_en",
            field=models.TextField(blank=True, null=True, verbose_name="Lunch options"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="schedule_de",
            field=models.TextField(blank=True, null=True, verbose_name="Schedule / Itinerary"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="schedule_en",
            field=models.TextField(blank=True, null=True, verbose_name="Schedule / Itinerary"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="venue_address_de",
            field=models.TextField(blank=True, null=True, verbose_name="Venue & address"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="venue_address_en",
            field=models.TextField(blank=True, null=True, verbose_name="Venue & address"),
        ),
        migrations.AlterField(
            model_name="tournamentregistration",
            name="registration_country",
            field=models.CharField(max_length=255, null=True, verbose_name="Country"),
        ),
    ]
