# Generated by Django 5.2.11 on 2026-06-03 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0020_remove_player_name_translations"),
        ("tournament", "0067_add_ema_id_to_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="non_playing_organizer",
            field=models.ForeignKey(
                blank=True,
                help_text="A player who organizes this tournament but does not compete. They receive the average of their AT points for this quota period.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organized_tournaments",
                to="player.player",
                verbose_name="Non-playing organizer",
            ),
        ),
    ]
