# Generated by Django 5.2.11 on 2026-06-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0069_tournament_non_playing_organizers_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="organizer_emails",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Email addresses (comma or newline separated) that receive a notice on each new registration.",
                verbose_name="Organizer notification emails",
            ),
        ),
    ]
