# Generated by Django 5.2.11 on 2026-06-15 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0070_tournament_organizer_emails"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentEmailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("confirmation", "Confirmation email (sent when a registration is approved)"),
                            ("registrant", "Registrant email (bulk send to all approved players)"),
                        ],
                        max_length=20,
                        verbose_name="Email type",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                (
                    "body",
                    models.TextField(
                        help_text="Supports {{first_name}} and {{last_name}} placeholders.", verbose_name="Body"
                    ),
                ),
                (
                    "reply_to",
                    models.EmailField(blank=True, default="", max_length=254, verbose_name="Reply-to address"),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to="tournament.tournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("tournament", "email_type")},
            },
        ),
    ]
