# Generated by Django 5.2.11 on 2026-09-10 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0071_tournamentemailtemplate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentregistration",
            name="pantheon_sync_error",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="tournamentregistration",
            name="pantheon_synced_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournamentregistration",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
