# Generated by Django 5.2.11 on 2026-09-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0072_tournamentregistration_pantheon_sync_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="general_information",
            field=models.TextField(blank=True, null=True, verbose_name="General information"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="general_information_de",
            field=models.TextField(blank=True, null=True, verbose_name="General information"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="general_information_en",
            field=models.TextField(blank=True, null=True, verbose_name="General information"),
        ),
    ]
