# Generated by Django 5.2.11 on 2026-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0073_tournament_general_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentapplication",
            name="general_information_de",
            field=models.TextField(blank=True, null=True, verbose_name="General information (DE)"),
        ),
        migrations.AddField(
            model_name="tournamentapplication",
            name="general_information_en",
            field=models.TextField(blank=True, null=True, verbose_name="General information (EN)"),
        ),
    ]
