# Generated by Django 5.2.11 on 2026-09-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0074_tournamentapplication_general_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="entry_fee",
            field=models.BooleanField(
                default=False, help_text="Track which registrants have paid the entry fee", verbose_name="Entry fee"
            ),
        ),
        migrations.AddField(
            model_name="tournamentregistration",
            name="has_paid",
            field=models.BooleanField(default=False, verbose_name="Paid"),
        ),
    ]
