# Generated by Django 5.2.11 on 2026-09-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0075_entry_fee_and_has_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="show_online_rank",
            field=models.BooleanField(
                default=False,
                help_text="Show the players' Dan rank in the participants table of the announcement",
                verbose_name="Show online rank",
            ),
        ),
    ]
