# Generated by Django 5.2.11 on 2026-09-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0076_tournament_show_online_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentregistration",
            name="waitlist_number",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Waitlist number"),
        ),
    ]
