# Generated by Django 5.2.11 on 2026-09-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0077_tournamentregistration_waitlist_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentemailtemplate",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("confirmation", "Confirmation email (sent when a registration is approved)"),
                    ("registrant", "Registrant email (bulk send to approved players only)"),
                    ("waitlist", "Waitlist email (sent when a registration is put on the waitlist)"),
                    ("all", "Email to all (bulk send to approved, waitlist and unapproved players)"),
                ],
                max_length=20,
                verbose_name="Email type",
            ),
        ),
    ]
