# Generated by Django 5.2.11 on 2026-10-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0079_tournament_entry_fee_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentemailtemplate",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("confirmation", "Confirmation email (sent when a registration is approved)"),
                    ("registrant", "Registrant email (bulk send to approved players only)"),
                    ("waitlist", "Waitlist email (sent when a registration is put on the waitlist)"),
                    ("all", "Email to all (bulk send to approved, waitlist and unapproved players)"),
                    ("unpaid", "Unpaid email (bulk send to approved players who have not paid)"),
                ],
                help_text="Saving a template never sends anything. Bulk types are sent from the tournament list: tick the tournament, then pick the matching action.",
                max_length=20,
                verbose_name="Email type",
            ),
        ),
    ]
