# Generated by Django 5.2.11 on 2026-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_auto_20210410_0502"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="country",
            name="name_ru",
        ),
        migrations.AddField(
            model_name="city",
            name="name_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="name_de",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
