# Generated by Django 5.2.11 on 2026-09-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0006_remove_city_country_name_translations"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreyConnector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("person_id", models.PositiveIntegerField(blank=True, null=True)),
                ("auth_token", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Frey connector",
                "verbose_name_plural": "Frey connector",
            },
        ),
    ]
